### ISSUE TITLE
TypeError: can only concatenate list (not "Tensor") to list

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/lightwood#115]
**To Reproduce**
1. Train new model with [wine_quality dataset](https://github.com/mindsdb/mindsdb-examples/blob/master/wine_quality/train.py)
2. TypeError: can only concatenate list (not "Tensor") to list

**Versions:**
 - Mindsdb version [1.11.8]
 - Lightwood Version [0.15.3]

**Stacktrace**

> ERROR:mindsdb-logger-453b0832-41cc-11ea-80b0-59af9f669202:libs/controllers/transaction.py:127 - Traceback (most recent call last):
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb/libs/controllers/transaction.py", line 123, in _call_phase_module
    return module(self.session, self)(**kwargs)
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb/libs/phases/base_module.py", line 54, in __call__
    ret = self.run(**kwargs)
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb/libs/phases/model_interface/model_interface.py", line 32, in run
    self.transaction.model_backend.train()
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb/libs/backends/lightwood.py", line 192, in train
    self.predictor.learn(from_data=train_df, test_data=test_df, callback_on_iter=self.callback_on_iter, eval_every_x_epochs=eval_every_x_epochs)
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/lightwood/api/predictor.py", line 212, in learn
    from_data_ds.prepare_encoders()
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/lightwood/api/data_source.py", line 271, in prepare_encoders
    encoder_instance.prepare_encoder(args[0], training_data=training_data)
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/lightwood/encoders/text/distilbert.py", line 178, in prepare_encoder
    real[i] = real[i] + target['encoded_output'][i]
TypeError: can only concatenate list (not "Tensor") to list

**Additional context**
Firstly I thought the problem is with parsing the data from the text column `Description` but it's not.
It looks like `real` value is an empty list and we concatenate it with a Tensor object.
real[] + tensor([0.0000, 3.5264, 0.0000]) => Error can only concatenate list (not "Tensor") to list

**Comment by George3d6** [comment]
Seems to be still an issue after the latest PR, looking into it now, rather weird.

**Comment by George3d6** [comment]
Pushed a hotfix for this.
