### ISSUE TITLE
KeyError when using small size datasets

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/lightwood#116]
**Describe the bug**
When you train the model with a dataset that contains less then 40 rows the bellow exception is thrown. It looks like test data_frame contains only two rows and  create_subsets will add only two Subsets.

**To Reproduce**
1.  Use dataset with less then 40 rows.
2. See error `KeyError: 3`

**Stacktracer**

> ERROR:mindsdb-logger-73439cea-4379-11ea-80b0-59af9f669202:libs/controllers/transaction.py:127 - Traceback (most recent call last):
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb/libs/controllers/transaction.py", line 123, in _call_phase_module
    return module(self.session, self)(**kwargs)
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb/libs/phases/base_module.py", line 54, in __call__
    ret = self.run(**kwargs)
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb/libs/phases/model_interface/model_interface.py", line 32, in run
    self.transaction.model_backend.train()
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb/libs/backends/lightwood.py", line 192, in train
    self.predictor.learn(from_data=train_df, test_data=test_df, callback_on_iter=self.callback_on_iter, eval_every_x_epochs=eval_every_x_epochs)
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/lightwood/api/predictor.py", line 291, in learn
    subset_test_ds = test_data_ds.subsets[subset_id]
KeyError: 3

**Comment by George3d6** [comment]
Fixed in PR #161
