### ISSUE TITLE
Unkown issues causing model not to be coppied 

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#135]
The model is not being coppied (fails with a pytroch error) when using the covid-19 dataset here:

The error is: https://github.com/mindsdb/mindsdb-examples/tree/master/others/covid19

```
Traceback (most recent call last):
  File "/home/george/mindsdb/mindsdb/libs/controllers/transaction.py", line 123, in _call_phase_module
    return module(self.session, self)(**kwargs)
  File "/home/george/mindsdb/mindsdb/libs/phases/base_module.py", line 54, in __call__
    ret = self.run(**kwargs)
  File "/home/george/mindsdb/mindsdb/libs/phases/model_interface/model_interface.py", line 32, in run
    self.transaction.model_backend.train()
  File "/home/george/mindsdb/mindsdb/libs/backends/lightwood.py", line 193, in train
    self.predictor.learn(from_data=train_df, test_data=test_df, callback_on_iter=self.callback_on_iter, eval_every_x_epochs=eval_every_x_epochs)
  File "/home/george/lightwood/lightwood/api/predictor.py", line 362, in learn
    best_selfaware_model = mixer.get_model_copy()
  File "/home/george/lightwood/lightwood/mixers/nn/nn.py", line 268, in get_model_copy
    net = copy.deepcopy(self.net)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/home/george/.local/lib/python3.7/site-packages/torch/tensor.py", line 44, in __deepcopy__
    raise RuntimeError("Only Tensors created explicitly by the user "
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mindsdb_acc.py", line 35, in <module>
    result = run()
  File "mindsdb_acc.py", line 16, in run
    backend = backend
  File "/home/george/mindsdb/mindsdb/libs/controllers/predictor.py", line 728, in learn
    Transaction(session=self, light_transaction_metadata=light_transaction_metadata, heavy_transaction_metadata=heavy_transaction_metadata, logger=self.log)
  File "/home/george/mindsdb/mindsdb/libs/controllers/transaction.py", line 53, in __init__
    self.run()
  File "/home/george/mindsdb/mindsdb/libs/controllers/transaction.py", line 325, in run
    self._execute_learn()
  File "/home/george/mindsdb/mindsdb/libs/controllers/transaction.py", line 189, in _execute_learn
    raise e
  File "/home/george/mindsdb/mindsdb/libs/controllers/transaction.py", line 174, in _execute_learn
    self._call_phase_module(clean_exit=False, module_name='ModelInterface', mode='train')
  File "/home/george/mindsdb/mindsdb/libs/controllers/transaction.py", line 131, in _call_phase_module
    raise Exception(error)
Exception: Could not load module ModelInterface
```

**Comment by George3d6** [comment]
Fixed by #136
