### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by madasebrof** [mindsdb/lightwood#156]
**Describe the bug**
After the 11 iteration, I get a divide by zero error. 

Note: was monitoring CPU/disk/memory during run. All fine.

**To Reproduce**
1. Run 
```
mdb = mindsdb.Predictor(name='test_model')

mdb.learn(
    from_data='data/train.csv', # the path to the file where we can learn from, (note: can be url)
    to_predict='target_col', # the column we want to learn to predict given all the data in the file
)
```
2. Works up until iteration 12
3. Bombs

**Expected behavior**
No error!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX - Catalina 10.15.4
 - Lightwood version [e.g. 0.1.8]
 - Python Version: 3.7.3

**Additional context**
```
INFO:root:Lightwood training, iteration 9, training error 0.017911437233315633
INFO:root:Subtest test error: 0.00031754489745206406 on subset 1, overall test error: 0.00031980572006325733
INFO:root:Model predictions and decoding completed
DEBUG:mindsdb-logger-db92b19c-8199-11ea-901a-60f81dca0766:libs/backends/lightwood.py:155 - We've reached training epoch nr 9 with an r2 score of 0.292 on the testing dataset

INFO:root:Lightwood training, iteration 10, training error 0.0185693815400826
INFO:root:Subtest test error: 0.0003235634083086932 on subset 1, overall test error: 0.00032630316417829743
INFO:root:Model predictions and decoding completed
DEBUG:mindsdb-logger-db92b19c-8199-11ea-901a-60f81dca0766:libs/backends/lightwood.py:155 - We've reached training epoch nr 10 with an r2 score of 0.291 on the testing dataset

INFO:root:Lightwood training, iteration 11, training error 0.01801437723119498
INFO:root:Subtest test error: 0.00031532185075232934 on subset 1, overall test error: 0.0003180302639134508
INFO:root:Model predictions and decoding completed
DEBUG:mindsdb-logger-db92b19c-8199-11ea-901a-60f81dca0766:libs/backends/lightwood.py:155 - We've reached training epoch nr 11 with an r2 score of 0.303 on the testing dataset

INFO:root:Lightwood training, iteration 12, training error 0.017850194683425094
INFO:root:Subtest test error: 0.0003127068075527959 on subset 1, overall test error: 0.00031501128266576224
ERROR:mindsdb-logger-db92b19c-8199-11ea-901a-60f81dca0766:libs/controllers/transaction.py:126 - Could not load module ModelInterface

ERROR:mindsdb-logger-db92b19c-8199-11ea-901a-60f81dca0766:libs/controllers/transaction.py:127 - Traceback (most recent call last):
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/controllers/transaction.py", line 123, in _call_phase_module
    return module(self.session, self)(**kwargs)
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/phases/base_module.py", line 54, in __call__
    ret = self.run(**kwargs)
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/phases/model_interface/model_interface.py", line 32, in run
    self.transaction.model_backend.train()
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/backends/lightwood.py", line 193, in train
    self.predictor.learn(from_data=train_df, test_data=test_df, callback_on_iter=self.callback_on_iter, eval_every_x_epochs=eval_every_x_epochs)
  File "anaconda3/lib/python3.7/site-packages/lightwood/api/predictor.py", line 405, in learn
    self.calculate_accuracy(test_data_ds))
  File "anaconda3/lib/python3.7/site-packages/lightwood/api/predictor.py", line 518, in calculate_accuracy
    predictions = self._mixer.predict(ds, include_encoded_predictions=True)
  File "anaconda3/lib/python3.7/site-packages/lightwood/mixers/nn/nn.py", line 184, in predict
    predictions[output_column]['selfaware_confidences'] = [1/x[k] for x in awareness_arr]
  File "anaconda3/lib/python3.7/site-packages/lightwood/mixers/nn/nn.py", line 184, in <listcomp>
    predictions[output_column]['selfaware_confidences'] = [1/x[k] for x in awareness_arr]
ZeroDivisionError: float division by zero


Traceback (most recent call last):
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/controllers/transaction.py", line 123, in _call_phase_module
    return module(self.session, self)(**kwargs)
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/phases/base_module.py", line 54, in __call__
    ret = self.run(**kwargs)
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/phases/model_interface/model_interface.py", line 32, in run
    self.transaction.model_backend.train()
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/backends/lightwood.py", line 193, in train
    self.predictor.learn(from_data=train_df, test_data=test_df, callback_on_iter=self.callback_on_iter, eval_every_x_epochs=eval_every_x_epochs)
  File "anaconda3/lib/python3.7/site-packages/lightwood/api/predictor.py", line 405, in learn
    self.calculate_accuracy(test_data_ds))
  File "anaconda3/lib/python3.7/site-packages/lightwood/api/predictor.py", line 518, in calculate_accuracy
    predictions = self._mixer.predict(ds, include_encoded_predictions=True)
  File "anaconda3/lib/python3.7/site-packages/lightwood/mixers/nn/nn.py", line 184, in predict
    predictions[output_column]['selfaware_confidences'] = [1/x[k] for x in awareness_arr]
  File "anaconda3/lib/python3.7/site-packages/lightwood/mixers/nn/nn.py", line 184, in <listcomp>
    predictions[output_column]['selfaware_confidences'] = [1/x[k] for x in awareness_arr]
ZeroDivisionError: float division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/controllers/transaction.py", line 174, in _execute_learn
    self._call_phase_module(clean_exit=False, module_name='ModelInterface', mode='train')
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/controllers/transaction.py", line 131, in _call_phase_module
    raise Exception(error)
Exception: Could not load module ModelInterface
ERROR:mindsdb-logger-db92b19c-8199-11ea-901a-60f81dca0766:libs/controllers/transaction.py:188 - Could not load module ModelInterface

Traceback (most recent call last):
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/controllers/transaction.py", line 123, in _call_phase_module
    return module(self.session, self)(**kwargs)
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/phases/base_module.py", line 54, in __call__
    ret = self.run(**kwargs)
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/phases/model_interface/model_interface.py", line 32, in run
    self.transaction.model_backend.train()
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/backends/lightwood.py", line 193, in train
    self.predictor.learn(from_data=train_df, test_data=test_df, callback_on_iter=self.callback_on_iter, eval_every_x_epochs=eval_every_x_epochs)
  File "anaconda3/lib/python3.7/site-packages/lightwood/api/predictor.py", line 405, in learn
    self.calculate_accuracy(test_data_ds))
  File "anaconda3/lib/python3.7/site-packages/lightwood/api/predictor.py", line 518, in calculate_accuracy
    predictions = self._mixer.predict(ds, include_encoded_predictions=True)
  File "anaconda3/lib/python3.7/site-packages/lightwood/mixers/nn/nn.py", line 184, in predict
    predictions[output_column]['selfaware_confidences'] = [1/x[k] for x in awareness_arr]
  File "anaconda3/lib/python3.7/site-packages/lightwood/mixers/nn/nn.py", line 184, in <listcomp>
    predictions[output_column]['selfaware_confidences'] = [1/x[k] for x in awareness_arr]
ZeroDivisionError: float division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "learn.py", line 9, in <module>
    to_predict='target_col', # the column we want to learn to predict given all the data in the file
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/controllers/predictor.py", line 728, in learn
    Transaction(session=self, light_transaction_metadata=light_transaction_metadata, heavy_transaction_metadata=heavy_transaction_metadata, logger=self.log)
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/controllers/transaction.py", line 53, in __init__
    self.run()
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/controllers/transaction.py", line 326, in run
    self._execute_learn()
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/controllers/transaction.py", line 189, in _execute_learn
    raise e
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/controllers/transaction.py", line 174, in _execute_learn
    self._call_phase_module(clean_exit=False, module_name='ModelInterface', mode='train')
  File "anaconda3/lib/python3.7/site-packages/mindsdb/libs/controllers/transaction.py", line 131, in _call_phase_module
    raise Exception(error)
Exception: Could not load module ModelInterface

```

**Comment by madasebrof** [comment]
It seems to be somewhat size related.

The original training set was an almost 400 MB csv file.

- Reduced to 1/100th the size (e.g. every 100 rows) and it worked fine (3.8 MB csv file).
- Reduced to 1 in 25 rows, (15 MB csv file) works fine.
- Reduced file to 1 row in 10 crashes (38 MB csv file), `ZeroDivisionError: float division by zero`

Maybe a different input method (e.g. DB, etc) would help???

**Comment by madasebrof** [comment]
FYI, so I altered the training data to have the target (e.g. `'to_predict'`) be a bool, (made it a binary classification problem), and now it was able to train with the full data set.

**Comment by George3d6** [comment]
Huh... curious, it's a silly bug related to the fact that I never assume the edge case in which the awareness network (one of our mechanisms for determining confidence) outputs exactly 0 (not, this isn't related to 0% confidence, it's closer to saying 100% confidence).

Should be fairly trivial to fix I'd wager.

Would you be able to provide dataset of which is this was trained? So I can make sure the bug is fixed

As an aside to your second comment: We don't support < 10 rows, so that's why 1 row crashes

**Comment by George3d6** [comment]
By the way, feel free to try again with the newest lightwood (`pip install lightwood==0.22.2`)

I'd still appreciate if you could share the datasets, assuming that it's public since the behavior exhibited does seem rather odd.

**Comment by torrmal** [comment]
@madasebrof can you confirm that is fixed?
