### ISSUE TITLE
GPU to CPU issue (when using mindsdb sql)

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#171]
```(pid=30874) ERROR:mindsdb-logger-core-logger:libs/controllers/transaction.py:131 - Traceback (most recent call last):
(pid=30874)   File "/home/george/mindsdb/mindsdb/libs/controllers/transaction.py", line 127, in _call_phase_module
(pid=30874)     return module(self.session, self)(**kwargs)
(pid=30874)   File "/home/george/mindsdb/mindsdb/libs/phases/base_module.py", line 54, in __call__
(pid=30874)     ret = self.run(**kwargs)
(pid=30874)   File "/home/george/mindsdb/mindsdb/libs/phases/model_interface/model_interface.py", line 34, in run
(pid=30874)     self.transaction.hmd['predictions'] = self.transaction.model_backend.predict()
(pid=30874)   File "/home/george/mindsdb/mindsdb/libs/backends/lightwood.py", line 223, in predict
(pid=30874)     self.predictor = lightwood.Predictor(load_from_path=self.transaction.lmd['lightwood_data']['save_path'])
(pid=30874)   File "/home/george/lightwood/lightwood/api/predictor.py", line 39, in __init__
(pid=30874)     self_dict = dill.load(pickle_in)
(pid=30874)   File "/home/george/.local/lib/python3.7/site-packages/dill/_dill.py", line 270, in load
(pid=30874)     return Unpickler(file, ignore=ignore, **kwds).load()
(pid=30874)   File "/home/george/.local/lib/python3.7/site-packages/dill/_dill.py", line 472, in load
(pid=30874)     obj = StockUnpickler.load(self)
(pid=30874)   File "/home/george/.local/lib/python3.7/site-packages/torch/storage.py", line 134, in _load_from_bytes
(pid=30874)     return torch.load(io.BytesIO(b))
(pid=30874)   File "/home/george/.local/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
(pid=30874)     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
(pid=30874)   File "/home/george/.local/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
(pid=30874)     result = unpickler.load()
(pid=30874)   File "/home/george/.local/lib/python3.7/site-packages/torch/serialization.py", line 665, in persistent_load
(pid=30874)     deserialized_objects[root_key] = restore_location(obj, location)
(pid=30874)   File "/home/george/.local/lib/python3.7/site-packages/torch/serialization.py", line 156, in default_restore_location
(pid=30874)     result = fn(storage, location)
(pid=30874)   File "/home/george/.local/lib/python3.7/site-packages/torch/serialization.py", line 132, in _cuda_deserialize
(pid=30874)     device = validate_cuda_device(location)
(pid=30874)   File "/home/george/.local/lib/python3.7/site-packages/torch/serialization.py", line 116, in validate_cuda_device
(pid=30874)     raise RuntimeError('Attempting to deserialize object on a CUDA '
(pid=30874) RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

Figure out replication later

**Comment by George3d6** [comment]
Related to us using fork rather than spanw, fixed in mindsdb.
