### ISSUE TITLE
CI fails on OSX due to transformers package

### ISSUE THREAD

**Issue by btseytlin** [mindsdb/lightwood#191]
Log:
```
Traceback (most recent call last):
  File "ci_tests.py", line 5, in <module>
    from lightwood import Predictor
  File "/Users/travis/build/mindsdb/lightwood/lightwood/__init__.py", line 9, in <module>
    from lightwood.encoders import BUILTIN_ENCODERS
  File "/Users/travis/build/mindsdb/lightwood/lightwood/encoders/__init__.py", line 5, in <module>
    from lightwood.encoders.text.infersent import InferSentEncoder
  File "/Users/travis/build/mindsdb/lightwood/lightwood/encoders/text/__init__.py", line 3, in <module>
    from lightwood.encoders.text.distilbert import DistilBertEncoder
  File "/Users/travis/build/mindsdb/lightwood/lightwood/encoders/text/distilbert.py", line 5, in <module>
    from transformers import DistilBertModel, DistilBertForSequenceClassification, AlbertModel, \
  File "/usr/local/lib/python3.7/site-packages/transformers/__init__.py", line 48, in <module>
    from .data import (
  File "/usr/local/lib/python3.7/site-packages/transformers/data/__init__.py", line 6, in <module>
    from .processors import (
  File "/usr/local/lib/python3.7/site-packages/transformers/data/processors/__init__.py", line 5, in <module>
    from .glue import glue_convert_examples_to_features, glue_output_modes, glue_processors, glue_tasks_num_labels
  File "/usr/local/lib/python3.7/site-packages/transformers/data/processors/glue.py", line 24, in <module>
    from ...tokenization_utils import PreTrainedTokenizer
  File "/usr/local/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 26, in <module>
    from .tokenization_utils_base import (
  File "/usr/local/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 31, in <module>
    from tokenizers import AddedToken
  File "/usr/local/lib/python3.7/site-packages/tokenizers/__init__.py", line 17, in <module>
    from .tokenizers import Tokenizer, Encoding, AddedToken
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/tokenizers/tokenizers.cpython-37m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/lib/python3.7/site-packages/tokenizers/tokenizers.cpython-37m-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/python3.7/site-packages/tokenizers/tokenizers.cpython-37m-darwin.so
/Users/travis/.travis/functions: line 607:  2293 Terminated: 15          travis_jigger "${!}" "${timeout}" "${cmd[@]}"
The command "if [ "$TRAVIS_OS_NAME" != "windows" ]; then travis_wait python3 ci_tests.py; fi" exited with 1.
```

**Comment by btseytlin** [comment]
Seems like it just plain doesnt work on python3.6 on Mac, but downgrading to python3.5 should solve the problem:
https://github.com/facebookresearch/fastText/issues/380

**Comment by ZoranPandovski** [comment]
We had a similar issue in the past. I think it is related to installing Python through brew. @btseytlin maybe it is better to try with 3.7.x version since lightwood will not work with older versions than 3.6

**Comment by btseytlin** [comment]
@ZoranPandovski We are already using Python 3.7.3 on mac in our CI, so it seems like something is broken for all Python versions after 3.6 :(

**Comment by George3d6** [comment]
Fixed
