### ISSUE TITLE
OverflowError in numeric encoder

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#244]
**Your Environment**

* Python version: 3.6.11
* Operating system: Ubuntu 16.04
* Lightwood version: 0.35.0

**Please describe your issue and how we can replicate it**
This issue had appeared in a propietary dataset before, and I couldn't replicate until now.

Basically, using the [micro mass](https://www.openml.org/d/1515) dataset as-is will raise an OverflowError shortly after training starts: 

```
Traceback (most recent call last):
  File "/MindsDB/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 164, in _run
    self._call_phase_module(module_name='ModelInterface', mode='train')
  File "/MindsDB/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 121, in _call_phase_module
    return module(self.session, self)(**kwargs)
  File "/MindsDB/mindsdb_native/mindsdb_native/libs/phases/base_module.py", line 54, in __call__
    ret = self.run(**kwargs)
  File "/MindsDB/mindsdb_native/mindsdb_native/libs/phases/model_interface/model_interface.py", line 31, in run
    self.transaction.model_backend.train()
  File "/MindsDB/mindsdb_native/mindsdb_native/libs/backends/lightwood.py", line 220, in train
    self.predictor.learn(from_data=train_df, test_data=test_df, callback_on_iter=self.callback_on_iter, eval_every_x_epochs=eval_every_x_epochs)
  File "/MindsDB/lightwood/lightwood/api/predictor.py", line 268, in learn
    self._mixer.fit(train_ds=from_data_ds ,test_ds=test_data_ds, callback=callback_on_iter_w_acc, stop_training_after_seconds=stop_training_after_seconds, eval_every_x_epochs=eval_every_x_epochs)
  File "/MindsDB/lightwood/lightwood/mixers/nn/nn.py", line 219, in fit
    callback(epoch, training_error, test_error, delta_mean)
  File "/MindsDB/lightwood/lightwood/api/predictor.py", line 266, in callback_on_iter_w_acc
    callback_on_iter(epoch, training_error, test_error, delta_mean, self.calculate_accuracy(test_data_ds))
  File "/MindsDB/lightwood/lightwood/api/predictor.py", line 393, in calculate_accuracy
    predicted = ds.get_decoded_column_data(output_column, predictions[output_column]['encoded_predictions'])
  File "/MindsDB/lightwood/lightwood/api/data_source.py", line 353, in get_decoded_column_data
    decoded_data = decoder_instance.decode(encoded_data)
  File "/MindsDB/lightwood/lightwood/encoders/numeric/numeric.py", line 102, in decode
    real_value = [math.exp(vector[i*2 + 1]) * sign for i in range(1 + self.extra_outputs)]
  File "/MindsDB/lightwood/lightwood/encoders/numeric/numeric.py", line 102, in <listcomp>
    real_value = [math.exp(vector[i*2 + 1]) * sign for i in range(1 + self.extra_outputs)]
OverflowError: math range error

```

**Comment by maximlopin** [comment]
There are large numbers in the dataframe that cause `math.exp(x)` to raise `OverflowError`.

`math.exp(math.log(x))` doesn't raise `OverflowError` for any numerical value in the dataframe though.

that's the only clue I have for now

**Comment by paxcema** [comment]
As of Lightwood 0.49.0, this issue is not happening anymore. Closing.
