### ISSUE TITLE
Error when using 'force_disable_cache' in time series task

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#341]
* Lightwood version: staging (post 0.51.0 release)

With us_consumption.csv dataset, training fails when using `advanced_args={'force_disable_cache': True}`, we get the following stack trace:

```
ERROR:mindsdb-logger-802183d6-3bdb-11eb-a895-4cedfb644c83---no_report:/MindsDB/mindsdb_native/mindsdb_native/libs/phases/model_interface/lightwood_backend.py:418 - Traceback (most recent call last):
  File "/MindsDB/mindsdb_native/mindsdb_native/libs/phases/model_interface/lightwood_backend.py", line 412, in train
    test_data=lightwood_test_ds
  File "/MindsDB/lightwood/lightwood/api/predictor.py", line 137, in learn
    self._mixer.fit(train_ds=train_ds, test_ds=test_ds)
  File "/MindsDB/lightwood/lightwood/mixers/base_mixer.py", line 37, in fit
    self._fit(train_ds, test_ds, **kwargs)
  File "/MindsDB/lightwood/lightwood/mixers/nn.py", line 146, in _fit
    input_sample, output_sample = train_ds[0]
  File "/MindsDB/lightwood/lightwood/api/data_source.py", line 225, in __getitem__
    sample[feature_set][col_name] = self.get_encoded_column_data(col_name, custom_data=custom_data)[0]
  File "/MindsDB/lightwood/lightwood/api/data_source.py", line 433, in get_encoded_column_data
    sublist = custom_data[col]
KeyError: '__mdb_ts_previous_Unemployment'
```

**Comment by paxcema** [comment]
Fixed in #397
