### ISSUE TITLE
KeyError for categorical time series targets with nr_predictions > 1

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#347]
As reported by @cosmoje, training a time series predictor with a categorical target and `nr_predictions > 1` can result in the following KeyError:

```
ERROR:mindsdb-logger-94092734-4525-11eb-97a4-293ded703082---34eb86e0-5318-4ee3-8117-a0c0d5162952:/anaconda3/lib/python3.8/site-packages/mindsdb_native/libs/phases/model_interface/lightwood_backend.py:418 - Traceback (most recent call last):
  File "/anaconda3/lib/python3.8/site-packages/mindsdb_native/libs/phases/model_interface/lightwood_backend.py", line 410, in train
    self.predictor.learn(
  File "/anaconda3/lib/python3.8/site-packages/lightwood/api/predictor.py", line 137, in learn
    self._mixer.fit(train_ds=train_ds, test_ds=test_ds)
  File "/anaconda3/lib/python3.8/site-packages/lightwood/mixers/base_mixer.py", line 37, in fit
    self._fit(train_ds, test_ds, **kwargs)
  File "/anaconda3/lib/python3.8/site-packages/lightwood/mixers/nn.py", line 342, in _fit
    self._nonpersistent['callback'](epoch, training_error, test_error, delta_mean, self.calculate_accuracy(test_ds))
  File "/anaconda3/lib/python3.8/site-packages/lightwood/mixers/nn.py", line 685, in calculate_accuracy
    accuracy = BaseMixer._apply_accuracy_function(
  File "/anaconda3/lib/python3.8/site-packages/lightwood/mixers/base_mixer.py", line 153, in _apply_accuracy_function
    sample_weight = [weight_map[val] for val in reals]
  File "/anaconda3/lib/python3.8/site-packages/lightwood/mixers/base_mixer.py", line 153, in <listcomp>
    sample_weight = [weight_map[val] for val in reals]
KeyError: '0'
```

It has to do with 0's being inserted in the additional target timestep columns not being part of the weight_map used in the accuracy function.

**Comment by paxcema** [comment]
Fixed in 0.55
