### ISSUE TITLE
Could not convert string to float error

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/lightwood#433]
Using [twitter airline sentiment](https://www.kaggle.com/crowdflower/twitter-airline-sentiment) dataset to predict the `airline_sentiment`, the bellow error happens on model training start:
```
Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForSequenceClassification: ['vocab_transform.weight', 'vocab_transform.bias', 'vocab_layer_norm.weight', 'vocab_layer_norm.bias', 'vocab_projector.weight', 'vocab_projector.bias']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['pre_classifier.weight', 'pre_classifier.bias', 'classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/opt/conda/lib/python3.8/site-packages/lightwood/encoders/text/helpers/pretrained_helpers.py:22: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
item['labels'] = torch.tensor(self.labels[idx])
ERROR:mindsdb-logger-1534b558-bd85-11eb-9ca6-0242ac110002---417f6474-2893-458f-8695-3859450f31dc:/opt/conda/lib/python3.8/site-packages/mindsdb_native/libs/controllers/transaction.py:173 - Could not load module ModelInterface
ERROR:mindsdb-logger-1534b558-bd85-11eb-9ca6-0242ac110002---417f6474-2893-458f-8695-3859450f31dc:/opt/conda/lib/python3.8/site-packages/mindsdb_native/libs/controllers/transaction.py:263 - could not convert string to float: '0.0 0.0'
Predictor learn error: could not convert string to float: '0.0 0.0'
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/mindsdb/interfaces/model/learn_process.py", line 67, in run_learn
mdb.learn(
File "/opt/conda/lib/python3.8/site-packages/mindsdb_native/libs/controllers/predictor.py", line 314, in learn
self.transaction.run()
File "/opt/conda/lib/python3.8/site-packages/mindsdb_native/libs/controllers/transaction.py", line 269, in run
self._run()
File "/opt/conda/lib/python3.8/site-packages/mindsdb_native/libs/controllers/transaction.py", line 265, in _run
raise e
File "/opt/conda/lib/python3.8/site-packages/mindsdb_native/libs/controllers/transaction.py", line 238, in _run
self._call_phase_module(module_name='ModelInterface', mode='train')
File "/opt/conda/lib/python3.8/site-packages/mindsdb_native/libs/controllers/transaction.py", line 170, in _call_phase_module
ret = module(self.session, self)(**kwargs)
File "/opt/conda/lib/python3.8/site-packages/mindsdb_native/libs/phases/base_module.py", line 53, in __call__
ret = self.run(**kwargs)
File "/opt/conda/lib/python3.8/site-packages/mindsdb_native/libs/phases/model_interface/model_interface.py", line 18, in run
self.transaction.model_backend.train()
File "/opt/conda/lib/python3.8/site-packages/mindsdb_native/libs/phases/model_interface/lightwood_backend.py", line 407, in train
lightwood_train_ds = lightwood.api.data_source.DataSource(
File "/opt/conda/lib/python3.8/site-packages/lightwood/api/data_source.py", line 116, in __init__
self.encoders = self._prepare_encoders()
File "/opt/conda/lib/python3.8/site-packages/lightwood/api/data_source.py", line 411, in _prepare_encoders
encoder_instance = self._prepare_column_encoder(config,
File "/opt/conda/lib/python3.8/site-packages/lightwood/api/data_source.py", line 359, in _prepare_column_encoder
encoder_instance.prepare(column_data, previous_target_data=training_data['previous'])
File "/opt/conda/lib/python3.8/site-packages/lightwood/encoders/time_series/rnn.py", line 130, in prepare
priming_data, lengths_data = self._prepare_raw_data(priming_data)
File "/opt/conda/lib/python3.8/site-packages/lightwood/encoders/time_series/rnn.py", line 101, in _prepare_raw_data
e = np.array(e, dtype=float)
ValueError: could not convert string to float: '0.0 0.0'
```

**Comment by paxcema** [comment]
We also got reports of a similar issue with this dataset: https://data.cityofchicago.org/Transportation/CTA-Ridership-Avg-Weekday-Bus-Stop-Boardings-in-Oc/mq3i-nnqe

The issue has to do with mishandling GPS coordinates. We should implement GPS type detection (potentially for UTM and UPS systems as well), to separate numerical components into different columns and delegating the task to numerical encoders.
