### ISSUE TITLE
Docs example does not work

### ISSUE THREAD

**Issue by FayazRahman** [mindsdb/lightwood#438]
**Your Environment**

* Python version: 3.8.5
* Operating system: Ubuntu 20.04.2 LTS
* Lightwood version: 0.68.0
* Additional info if applicable:

**Please describe your issue and how we can replicate it**
I came across lightwood and was following the example at https://docs.mindsdb.com/lightwood/info/ Calling the learn method of Predictor does not seem to work proper.

```
from lightwood import Predictor
import pandas
sensor3_predictor = Predictor(output=['sensor3'])
sensor3_predictor.learn(from_data=pandas.read_csv('sensor_data.csv))
```

Here's 'sensor_data.csv':

```
sensor1,sensor2,sensor3
1,-1,-1
0,1,0
-1,-1,-1
```

Above code gives:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fayazrahman4u/.local/lib/python3.8/site-packages/lightwood/api/predictor.py", line 138, in learn
    self._mixer.fit(train_ds=train_ds, test_ds=test_ds)
  File "/home/fayazrahman4u/.local/lib/python3.8/site-packages/lightwood/mixers/base_mixer.py", line 39, in fit
    self._fit(train_ds, test_ds, **kwargs)
  File "/home/fayazrahman4u/.local/lib/python3.8/site-packages/lightwood/mixers/nn.py", line 288, in _fit
    subset_test_ds = test_ds.subsets[subset_id]
KeyError: 1
```

**Comment by ZoranPandovski** [comment]
Hello @FayazRahman I just check the example and it works. By looking at the above error I guess you are trying with the dataset that contains only 3 rows which are not enough to train the new Predictor. In the example we are just showing the portion of the data, so you need to use more data. Maybe it would be good if we change the example or include a link to the sensors dataset.

**Comment by FayazRahman** [comment]
@ZoranPandovski Oh thanks and I guess it's due to the splitting?

**Comment by ZoranPandovski** [comment]
Yes, also it doesn't make sense to train a model with just a few rows. I think in MindsDB we already have validation for this kind of scenario, so users can have a descriptive message. @George3d6 Maybe we need to add that in Lightwood too?
