### ISSUE TITLE
Can't encode target value: 0.0 when training  ts model

### ISSUE THREAD

**Issue by ilia-tsyplenkov** [mindsdb/lightwood#495]
## Your Environment
* Python version: 3.8.10
* Operating system: Ubuntu 20.04
* Lightwood version: 1.1.0 (staging)

## Describe your issue
Error while training TS model

## How can we replicate it? 
- Run mindsdb
- upload covid dataset
- try to train a new ts model (window size - 10, order_by - time, group_by - state) target - pnew_case
Note that it finishes with error (mindsdb log):
```
INFO:lightwood-17320:time series encoder epoch [35/100000] average_loss = 0.0009831745694894151
INFO:lightwood-17320:Featurizing the data
INFO:lightwood-17320:Training the models
/home/itsyplen/repos/work/MindsDB/mindsdb_env/lib/python3.8/site-packages/lightgbm/engine.py:148: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning("Found `{}` in params. Will use it instead of argument".format(alias))
[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
WARNING:lightwood-17320:LightGBM running on CPU, this somewhat slower than the GPU version, consider using a GPU instead
WARNING:lightwood-17320:Exception: Can't encode target value: 0.0 when training model: <lightwood.model.neural.Neural object at 0x7f14ef8b1310>
Process LearnProcess-1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/itsyplen/repos/work/MindsDB/mindsdb/mindsdb/interfaces/model/learn_process.py", line 181, in run
    run_learn(*self._args)
  File "/home/itsyplen/repos/work/MindsDB/mindsdb/mindsdb/interfaces/model/learn_process.py", line 107, in run_learn
    run_fit(predictor_record.id, df)
  File "/home/itsyplen/repos/work/MindsDB/mindsdb/mindsdb/interfaces/model/learn_process.py", line 98, in run_fit
    raise e
  File "/home/itsyplen/repos/work/MindsDB/mindsdb/mindsdb/interfaces/model/learn_process.py", line 77, in run_fit
    predictor.learn(df)
  File "/tmp/d66af8831b7218e1ef8ff82b4cfb1d0e8e575b6a20775b0916310143844882693.py", line 164, in learn
    raise e
  File "/tmp/d66af8831b7218e1ef8ff82b4cfb1d0e8e575b6a20775b0916310143844882693.py", line 159, in learn
    model.fit(train_data)
  File "/home/itsyplen/repos/work/MindsDB/lightwood/lightwood/model/neural.py", line 256, in fit
    self._init_net(ds_arr)
  File "/home/itsyplen/repos/work/MindsDB/lightwood/lightwood/model/neural.py", line 225, in _init_net
    net_kwargs = {'input_size': len(ds_arr[0][0][0]),
  File "/home/itsyplen/repos/work/MindsDB/lightwood/lightwood/data/encoded_ds.py", line 59, in __getitem__
    encoded_tensor = self.encoders[col].encode(data, **kwargs)[0]
  File "/home/itsyplen/repos/work/MindsDB/lightwood/lightwood/encoder/numeric/ts_numeric.py", line 52, in encode
    raise Exception(f'Can\'t encode target value: {real}')
Exception: Can't encode target value: 0.0
```

**note that training of forecast model finishes with success**

**Comment by ilia-tsyplenkov** [comment]
[covid_ICU_raw.csv](https://github.com/mindsdb/mindsdb/files/7038000/covid_ICU_raw.csv)

**COVID DATASOURCE**

**Comment by ilia-tsyplenkov** [comment]
:+1:
