### ISSUE TITLE
IndexError in AutoARIMA if process is constant

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#554]
Reported in community slack:

It appears that if the `sktime` mixer for time series ends up returning a (0, 0, 0) model, then the following error may arise:

```
/usr/lib/mindsdb/lib/python3.8/site-packages/pmdarima/arima/auto.py:460: UserWarning: Input time-series is completely constant; returning a (0, 0, 0) ARMA.
  warnings.warn('Input time-series is completely constant; '
WARNING:lightwood-107:Exception: too many indices for array: array is 0-dimensional, but 1 were indexed when training model: <lightwood.model.sktime.SkTime object at 0x7fb6c3dabd60>
Process LearnProcess-2:2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/mindsdb/interfaces/model/learn_process.py", line 181, in run
    run_learn(*self._args)
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/mindsdb/interfaces/model/learn_process.py", line 107, in run_learn
    run_fit(predictor_record.id, df)
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/mindsdb/interfaces/model/learn_process.py", line 98, in run_fit
    raise e
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/mindsdb/interfaces/model/learn_process.py", line 77, in run_fit
    predictor.learn(df)
  File "/tmp/d6a5ef10befc5b9397a674bc37e43af56173ea02cfc4f2af16328395124670558.py", line 149, in learn
    raise e
  File "/tmp/d6a5ef10befc5b9397a674bc37e43af56173ea02cfc4f2af16328395124670558.py", line 144, in learn
    model.fit(train_data)
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/lightwood/model/sktime.py", line 58, in fit
    self.models[group].fit(series)
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/sktime/forecasting/base/_base.py", line 118, in fit
    self._fit(y=y, X=X, fh=fh)
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/sktime/forecasting/base/adapters/_pmdarima.py", line 46, in _fit
    self._forecaster.fit(y, X=X, **fit_params)
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/pmdarima/arima/auto.py", line 177, in fit
    self.model_ = auto_arima(
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/pmdarima/arima/auto.py", line 465, in auto_arima
    fit_partial(
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/pmdarima/arima/_auto_solvers.py", line 506, in _fit_candidate_model
    fit.fit(y, X=X, **fit_params)
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/pmdarima/arima/arima.py", line 482, in fit
    self._fit(y, X, **fit_args)
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/pmdarima/arima/arima.py", line 405, in _fit
    fit, self.arima_res_ = _fit_wrapper()
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/pmdarima/arima/arima.py", line 393, in _fit_wrapper
    return arima, arima.fit(start_params=start_params,
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 643, in fit
    start_params = self.start_params
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/statsmodels/tsa/statespace/sarimax.py", line 953, in start_params
    params_variance) = self._conditional_sum_squares(
  File "/usr/lib/mindsdb/lib/python3.8/site-packages/statsmodels/tsa/statespace/sarimax.py", line 843, in _conditional_sum_squares
    Y = endog[r:]
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

```

**Comment by George3d6** [comment]
Seems bad (?) in that it could affect a lot of different ts problems, I'd be in favour of holding the release of `1.3.0` until it's fixed.
