### ISSUE TITLE
home rentals can not train

### ISSUE THREAD

**Issue by fromdavelewis** [mindsdb/lightwood#560]
Trying to train home_rentals on alpha, the predictor can not be created (via GUI or SQL) with the following stack trace:

INFO:lightwood-4909:Infering type for: days_on_market
INFO:lightwood-4909:Column days_on_market has data type integer
INFO:lightwood-4909:Infering type for: rental_price
INFO:lightwood-4909:Column rental_price has data type integer
INFO:lightwood-4908:Infering type for: location
INFO:lightwood-4908:Column location has data type categorical
INFO:lightwood-4905:Infering type for: number_of_rooms
INFO:lightwood-4905:Column number_of_rooms has data type categorical
INFO:lightwood-4910:Infering type for: initial_price
INFO:lightwood-4910:Column initial_price has data type integer
INFO:lightwood-4911:Infering type for: neighborhood
INFO:lightwood-4906:Infering type for: sqft
INFO:lightwood-4906:Column sqft has data type integer
INFO:lightwood-4907:Infering type for: number_of_bathrooms
INFO:lightwood-4907:Column number_of_bathrooms has data type binary
INFO:lightwood-4911:Column neighborhood has data type categorical
INFO:lightwood-4885:Starting statistical analysis
Process LearnProcess-1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/mindsdb/interfaces/model/learn_process.py", line 178, in run
    run_learn(*self._args)
  File "/usr/local/lib/python3.6/dist-packages/mindsdb/interfaces/model/learn_process.py", line 101, in run_learn
    run_generate(df, problem_definition, name, company_id, datasource_id)
  File "/usr/local/lib/python3.6/dist-packages/mindsdb/utilities/functions.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mindsdb/interfaces/model/learn_process.py", line 44, in run_generate
    json_ai = lightwood.json_ai_from_problem(df, problem_definition)
  File "/usr/local/lib/python3.6/dist-packages/lightwood/api/high_level.py", line 50, in json_ai_from_problem
    df, type_information.dtypes, type_information.identifiers, problem_definition)
  File "/usr/local/lib/python3.6/dist-packages/lightwood/data/statistical_analysis.py", line 85, in statistical_analysis
    problem_definition.anomaly_detection)
  File "/usr/local/lib/python3.6/dist-packages/lightwood/data/cleaner.py", line 57, in cleaner
    ).replace({nan_val: None})
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/series.py", line 4582, in replace
    method=method,
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 6507, in replace
    to_replace, value, inplace=inplace, limit=limit, regex=regex
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/series.py", line 4582, in replace
    method=method,
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 6553, in replace
    regex=regex,
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/internals/managers.py", line 651, in replace_list
    masks = [comp(s, mask, regex) for s in src_list]
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/internals/managers.py", line 651, in <listcomp>
    masks = [comp(s, mask, regex) for s in src_list]
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/internals/managers.py", line 645, in comp
    return _compare_or_regex_search(values, s, regex, mask)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/internals/managers.py", line 2001, in _compare_or_regex_search
    _check_comparison_types(False, a, b)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/internals/managers.py", line 1981, in _check_comparison_types
    f"Cannot compare types {repr(type_names[0])} and {repr(type_names[1])}"
TypeError: Cannot compare types 'ndarray(dtype=int64)' and 'str'

**Comment by StpMax** [comment]
There is two other issues that may be related to lightwood:
https://github.com/mindsdb/mindsdb/runs/3792809444#step:7:272
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/mindsdb/mindsdb/mindsdb/streams/stream_controller.py", line 85, in _make_predictions
    preds = self.model_interface.predict(self.predictor, when_data, 'dict')
  File "/home/runner/work/mindsdb/mindsdb/mindsdb/interfaces/model/model_interface.py", line 12, in wrapper
    return getattr(self.model_interface, name)(*args, **kwargs)
  File "/home/runner/work/mindsdb/mindsdb/mindsdb/interfaces/model/model_interface.py", line 31, in predict
    return self.controller.predict(*args, **kwargs)
  File "/home/runner/work/mindsdb/mindsdb/mindsdb/utilities/functions.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "/home/runner/work/mindsdb/mindsdb/mindsdb/interfaces/model/model_controller.py", line 146, in predict
    predictions = self.predictor_cache[name]['predictor'].predict(df)
  File "/tmp/7da0628d457ce40721b46c948489d7e3e645260fb59140a516333607127619205.py", line 279, in predict
    df = self.ensemble(encoded_ds)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/lightwood/ensemble/best_of.py", line 41, in __call__
    return self.mixers[self.best_index](ds, predict_proba=predict_proba)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/lightwood/mixer/regression.py", line 52, in __call__
    Yh = self.model.predict(X)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sklearn/linear_model/_base.py", line 238, in predict
    return self._decision_function(X)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sklearn/linear_model/_base.py", line 222, in _decision_function
    dense_output=True) + self.intercept_
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sklearn/utils/extmath.py", line 152, in safe_sparse_dot
    ret = a @ b
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 14 is different from 8)
```
https://github.com/mindsdb/mindsdb/runs/3792809362#step:7:194
```
    run_learn(*self._args)
  File "/home/runner/work/mindsdb/mindsdb/mindsdb/interfaces/model/learn_process.py", line 101, in run_learn
    run_generate(df, problem_definition, name, company_id, datasource_id)
  File "/home/runner/work/mindsdb/mindsdb/mindsdb/utilities/functions.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "/home/runner/work/mindsdb/mindsdb/mindsdb/interfaces/model/learn_process.py", line 44, in run_generate
    json_ai = lightwood.json_ai_from_problem(df, problem_definition)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/lightwood/api/high_level.py", line 50, in json_ai_from_problem
    df, type_information.dtypes, type_information.identifiers, problem_definition)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/lightwood/data/statistical_analysis.py", line 85, in statistical_analysis
    problem_definition.anomaly_detection)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/lightwood/data/cleaner.py", line 57, in cleaner
    ).replace(***nan_val: None***)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/pandas/core/series.py", line 4582, in replace
    method=method,
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/pandas/core/generic.py", line 6507, in replace
    to_replace, value, inplace=inplace, limit=limit, regex=regex
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/pandas/core/series.py", line 4582, in replace
    method=method,
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/pandas/core/generic.py", line 6553, in replace
    regex=regex,
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 651, in replace_list
    masks = [comp(s, mask, regex) for s in src_list]
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 651, in <listcomp>
    masks = [comp(s, mask, regex) for s in src_list]
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 645, in comp
    return _compare_or_regex_search(values, s, regex, mask)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 2001, in _compare_or_regex_search
    _check_comparison_types(False, a, b)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1981, in _check_comparison_types
    f"Cannot compare types ***repr(type_names[0])*** and ***repr(type_names[1])***"
```

**Comment by George3d6** [comment]
Alright, thought I had fixed this, apparently, I didn't. The issue seems to be with the format of the data coming from Postgres, combined (potentially, probably) with an issue in the new staging and/or new dependencies (though I tend to think it's a staging issue).

Data from e.g. a file doesn't trigger the issue, which is odd because the type detected are correct.

Haven't replicated locally yet, in progress.

@StpMax 's issue is dependency related but doesn't trigger on staging or in the CI env, so for now I think we can ignore since long-term we have to deprecate 3.6 as pandas seems to have "dropped support" given that their latest releases don't work /w it.
