### ISSUE TITLE
Replace pandas

### ISSUE THREAD

**Issue by George3d6** [mindsdb/lightwood#567]
Reasons:
1. Pandas is slow, benchmarking performance ends up with *most* time in lightwood when predicting being often spent in data frame specific functions
2. Pandas has certain bugs. Some examples (will list more):
- Completely different behaviors between versions. E.g. failures for stat analysis on 1.1.3, and running perfectly on 1.3.3
- Changing behavior of version to version (check how to replace NaN is None in pandas, you'll find 6x different methods, 5x worked before and now don't)
- "Hidden" operations that go against user specifications (e.g. automatically deciding on a column's type *and* modifying the values in that column to fit the type when a list or np array gets assigned to a column)
- Inconsistent behaviour when using standard array dunder ops, sometimes they work just like a np.array/list, other times they do something completely different. This has caused hidden bugs before (see .e.g issues with TS encoders we had before making the array encoder handle arrays)

**Comment by George3d6** [comment]
```
Index(['id', 'url_legal', 'license', 'excerpt', 'target', 'standard_error'], dtype='object')
INFO:lightwood-345595:Analyzing a sample of 2478
INFO:lightwood-345595:from a total population of 2834, this is equivalent to 87.4% of your data.
INFO:lightwood-345595:Using 7 processes to deduct types.
INFO:lightwood-345595:Infering type for: id
INFO:lightwood-345595:Infering type for: url_legal
INFO:lightwood-345595:Infering type for: license
INFO:lightwood-345595:Infering type for: target
INFO:lightwood-345595:Infering type for: standard_error
INFO:lightwood-345595:Infering type for: excerpt
INFO:lightwood-345595:Column target has data type float
INFO:lightwood-345595:Column standard_error has data type float
INFO:lightwood-345595:Column license has data type categorical
INFO:lightwood-345595:Doing text detection for column: url_legal
INFO:lightwood-345595:Doing text detection for column: id
INFO:lightwood-345595:Doing text detection for column: excerpt
INFO:lightwood-345595:Column url_legal has data type categorical



[nltk_data] Downloading package stopwords to /home/george/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

[nltk_data] Downloading package stopwords to /home/george/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

INFO:lightwood-345595:Column id has data type categorical

WARNING:lightwood-345595:Column id is an identifier of type "Hash-like identifier"
INFO:lightwood-345595:Starting statistical analysis
excerpt nan <class 'float'>
excerpt nan <class 'str'>
excerpt NaN <class 'str'>
excerpt Nan <class 'str'>
excerpt None <class 'str'>
target nan <class 'float'>
target nan <class 'str'>
Traceback (most recent call last):
  File "lw_rep.py", line 32, in <module>
    JsonAI = json_ai_from_problem(data, problem_definition)
  File "/home/george/lightwood/lightwood/api/high_level.py", line 49, in json_ai_from_problem
    statistical_analysis = lightwood.data.statistical_analysis(
  File "/home/george/lightwood/lightwood/data/statistical_analysis.py", line 83, in statistical_analysis
    df = cleaner(data, dtypes, problem_definition.pct_invalid, problem_definition.ignore_features,
  File "/home/george/lightwood/lightwood/data/cleaner.py", line 58, in cleaner
    data[col] = data[col].replace({nan_val: None})
  File "/home/george/.local/lib/python3.8/site-packages/pandas/core/series.py", line 4563, in replace
    return super().replace(
  File "/home/george/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6500, in replace
    return self.replace(
  File "/home/george/.local/lib/python3.8/site-packages/pandas/core/series.py", line 4563, in replace
    return super().replace(
  File "/home/george/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6543, in replace
    new_data = self._mgr.replace_list(
  File "/home/george/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 642, in replace_list
    masks = [comp(s, mask, regex) for s in src_list]
  File "/home/george/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 642, in <listcomp>
    masks = [comp(s, mask, regex) for s in src_list]
  File "/home/george/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 636, in comp
    return _compare_or_regex_search(values, s, regex, mask)
  File "/home/george/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1992, in _compare_or_regex_search
    _check_comparison_types(False, a, b)
  File "/home/george/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1971, in _check_comparison_types
    raise TypeError(
TypeError: Cannot compare types 'ndarray(dtype=float64)' and 'str'
```

Will write out issue above later, copy pasting the error log here so I don't forget.

**Comment by George3d6** [comment]
Some operations done inplace by default, others aren't

**Comment by George3d6** [comment]
Modin -- same issues due to compatibility
Dask -- might be worth pursuing
