### ISSUE TITLE
Error "Please specify a custom accuracy function for output type short_text"

### ISSUE THREAD

**Issue by StpMax** [mindsdb/lightwood#580]
Initially I tried to repeat [this issue](https://github.com/mindsdb/mindsdb/issues/1451). During that i tried to make predictor with target 'libgeo', but during 'generation' step i got error from lightwood:
```
Traceback (most recent call last):
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb/mindsdb/interfaces/model/learn_process.py", line 93, in run_learn
    run_generate(df, problem_definition, predictor_id)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb/mindsdb/utilities/functions.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb/mindsdb/interfaces/model/learn_process.py", line 45, in run_generate
    json_ai = lightwood.json_ai_from_problem(df, problem_definition)
  File "/home/maxs/dev/mdb/venv38/sources/lightwood/lightwood/api/high_level.py", line 58, in json_ai_from_problem
    json_ai = generate_json_ai(
  File "/home/maxs/dev/mdb/venv38/sources/lightwood/lightwood/api/json_ai.py", line 311, in generate_json_ai
    raise Exception(f'Please specify a custom accuracy function for output type {output_dtype}')
Exception: Please specify a custom accuracy function for output type short_text
```

**Comment by ZoranPandovski** [comment]
This was reported again, copying the user's info: 

```
Our dataset is a news article dataset consisting of news title, description and topics .Title,description and topics are text columns. The output type of topic must be categorical/text and it showed now as short_text.
```

**Comment by George3d6** [comment]
If this is a "categories get misclassified as text" issue, I need the original data to replicate.
