### ISSUE TITLE
`nan` issue in time series integration test

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#725]
Seen in #720:

```
[3, 5, 6, 16, 20, 23, 25, 36, 41, 48, 50, 51, 59, 63, 66, 72, 75, 77, 78, 86, 90, 93, 100, 106, 113] 
19267
======================================================================
19268
 [15, 9, 27, 11, 8, -7, -11, 0, -12, -3, -3, -13, -13, -17, -6, -15, -21, -16, -7, -12, -13, -16, -10, -10, -10]
19269
ERROR: test_0_time_series_grouped_regression (integration.advanced.test_timeseries.TestTimeseries)
19270
Categorial encoder accuracy for: -2.9349260375887116 on testing dataset
19271
Test grouped numerical predictions, with anomalies and forecast horizon > 1
19272
tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.2305, 0.0000],
19273
----------------------------------------------------------------------
19274
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.3428, 0.0000],
19275
Traceback (most recent call last):
19276
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
19277
  File "/home/runner/work/lightwood/lightwood/tests/integration/advanced/test_timeseries.py", line 82, in test_0_time_series_grouped_regression
19278
        ...,
19279
    preds = pred.predict(test)
19280
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
19281
  File "/tmp/1b8b41bc090a39b528739afbee9d245a707e58d1c201438916360692318914034.py", line 470, in predict
19282
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
19283
    df = self.ensemble(encoded_ds, args=self.pred_args)
19284
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]])
19285
  File "/home/runner/work/lightwood/lightwood/lightwood/ensemble/best_of.py", line 61, in __call__
19286
time series encoder epoch [1/100000] average_loss = 5.514529108814895
19287
    raise(e)
19288
time series encoder epoch [2/100000] average_loss = 1.4783096424117685
19289
  File "/home/runner/work/lightwood/lightwood/lightwood/ensemble/best_of.py", line 58, in __call__
19290
time series encoder epoch [3/100000] average_loss = 1.2493549716472625
19291
    return mixer(ds, args=args)
19292
  File "/home/runner/work/lightwood/lightwood/lightwood/mixer/neural.py", line 319, in __call__
19293
    for idx, (X, Y) in enumerate(ds):
19294
  File "/home/runner/work/lightwood/lightwood/lightwood/data/encoded_ds.py", line 74, in __getitem__
19295
    encoded_tensor = self.encoders[col].encode(data, **kwargs)[0]
19296
  File "/home/runner/work/lightwood/lightwood/lightwood/encoder/numeric/ts_array_numeric.py", line 42, in encode
19297
    ret.append(self.sub_encoder.encode([data_point], dependency_data=dependency_data))
19298
  File "/home/runner/work/lightwood/lightwood/lightwood/encoder/numeric/ts_numeric.py", line 56, in encode
19299
    raise Exception(f'Can\'t encode target value: {real}')
19300
Exception: Can't encode target value: nan
```

#720 implements a `pass` that is only a temporal fix.

**Comment by paxcema** [comment]
Additional information: this test passes locally on a MacBook Pro. Maybe GPU-related?

**Comment by paxcema** [comment]
Okay, I _think_ this is actually expected behavior because the `nan` comes from missing information in the columns with future values (which, at predict time, are not available). Will double check and propose a fix PR.
